# Generated by Django 2.2.6 on 2019-12-23 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191223_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
