# Generated by Django 2.2.6 on 2019-12-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191224_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['content_type'], 'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_time'], 'verbose_name': '文章评论', 'verbose_name_plural': '文章评论'},
        ),
        migrations.AlterModelOptions(
            name='friendlink',
            options={'ordering': ['create_time'], 'verbose_name': '友情链接', 'verbose_name_plural': '友情链接'},
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='create_time',
            new_name='comment_time',
        ),
        migrations.RenameField(
            model_name='friendlink',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='friendlink',
            old_name='name',
            new_name='site_name',
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AlterModelTable(
            name='carousel',
            table='carousel',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='friendlink',
            table='friend_link',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
