# Generated by Django 2.2.6 on 2019-12-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '基本信息', 'verbose_name_plural': '基本信息'},
        ),
    ]
